### ISSUE TITLE
feat: Hear It From Our Clients 데스크탑뷰 만들기

### ISSUE THREAD

**Issue by KimRiun** [PDA-coworKing/coworKingSpace#1]
## 💡 Feature issue
- Hear It From Our Clients 섹션의 데스크탑뷰 만들기

## ✅ To-do
- [x] 카드 모아져있는 모습
- [x] 카드 펼져칠 때 애니메이션
- [x] 카드가 펼져친 모습
- [x] 카드 hover 애니메이션

**Comment by Nahyeonnnn** [comment]
구현 완료 ><
