### ISSUE TITLE
feat: Explore Cowork Through Our Lens 데스크탑 뷰 만들기

### ISSUE THREAD

**Issue by KimRiun** [PDA-coworKing/coworKingSpace#21]
## 💡 Feature issue
- Explore Cowork Through Our Lens 데스크탑 뷰 만들기

## ✅ To-do
- [x] 섹션 설명 추가
- [x] 섹션 제목 추가
- [x] 섹션 info 추가
- [x] Explore 버튼 추가
- [x] 영상 삽입
