### ISSUE TITLE
feat: Your Roadmap to Coworking Clarity 데스크탑 뷰 만들기

### ISSUE THREAD

**Issue by Nahyeonnnn** [PDA-coworKing/coworKingSpace#6]
## 💡 Feature issue
- roadmap 섹션의 데스크탑 뷰 만들기

## ✅ To-do
- [x] 제목과 본문의 css 스타일 적용
- [x] 첫번째 항목은 토글 구현
- [x] 토글 열 때 애니메이션 추가하기

**Comment by subsub97** [comment]
이슈 관리 폼 미쳤다.....
